package cubepay.com.enums;

public enum ConfigProperties {
    REGISTEREDMOBILENO,
    REGISTEREDMOBILENO2,
    UNREGISTEREDMOBILENO,
    SHORTMOBILENO,
    PASSWORD,
    WRONGPASSWORD,
    TENDIGITPASSWORD,
    MODE,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    ALPHAPASSWORD,
    SPECCHARPASSWORD,


}
